### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by dredhorse** [maruohon/environmentalcreepers#3]
Hi,

is this you or nature destruction?

`[12:13:34] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.ExplosionEvent$Detonate@2554c73d:
java.lang.NoSuchFieldError: TYPE_OVERWORLD
	at quarris.naturesdestruction.block.tile.TileExplosionGenerator.isCorrectWorldType(TileExplosionGenerator.java:114) ~[TileExplosionGenerator.class:?]
	at quarris.naturesdestruction.event.GenEvents.onExplosionEvent(GenEvents.java:34) ~[GenEvents.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1280_GenEvents_onExplosionEvent_Detonate.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onExplosionDetonate(ForgeEventFactory.java:568) [ForgeEventFactory.class:?]
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:134) [amp.class:?]
	at fi.dy.masa.environmentalcreepers.event.ExplosionEventHandler.replaceExplosion(ExplosionEventHandler.java:180) [ExplosionEventHandler.class:?]
	at fi.dy.masa.environmentalcreepers.event.ExplosionEventHandler.onExplosionStart(ExplosionEventHandler.java:73) [ExplosionEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1039_ExplosionEventHandler_onExplosionStart_Start.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onExplosionStart(ForgeEventFactory.java:552) [ForgeEventFactory.class:?]
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1168) [oo.class:?]
	at net.minecraft.world.World.func_72876_a(World.java:2300) [amu.class:?]
	at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(EntityCreeper.java:271) [acs.class:?]
	at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(EntityCreeper.java:168) [acs.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:1993) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832) [oo.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1955) [amu.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1759) [amu.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by dredhorse** [comment]
https://github.com/Quarris/NaturesDestruction/issues/1#issue-391665596

**Comment by dredhorse** [comment]
not your fault.
